class FoodCatalog:
    def __init__(self):
        self.food_catalog = {
            # VEGETABLES
            "potato": ["vegetable", "root"],
            "potatoes": ["vegetable", "root"],
            "potatoe": ["vegetable", "root"],
            "potatos": ["vegetable", "root"],
            "russet potato": ["vegetable", "root"],
            "russet potatoes": ["vegetable", "root"],
            "russet potatos": ["vegetable", "root"],
            "yukon gold potato": ["vegetable", "root"],
            "yukon gold potatoes": ["vegetable", "root"],
            "yukon gold potatos": ["vegetable", "root"],
            "fingerling potato": ["vegetable", "root"],
            "fingerling potatoes": ["vegetable", "root"],
            "fingerling potatos": ["vegetable", "root"],
            "sweet potato": ["vegetable", "root"],
            "sweet potatoes": ["vegetable", "root"],
            "sweet potatos": ["vegetable", "root"],
            "beet": ["vegetable", "root"],
            "beets": ["vegetable", "root"],
            "carrot": ["vegetable", "root"],
            "carrots": ["vegetable", "root"],
            "onion": ["vegetable", "bulb"],
            "onions": ["vegetable", "bulb"],
            "shallot": ["vegetable", "bulb"],
            "shallots": ["vegetable", "bulb"],
            "green onion": ["vegetable", "bulb"],
            "green onions": ["vegetable", "bulb"],
            "red onion": ["vegetable", "bulb"],
            "red onions": ["vegetable", "bulb"],
            "yellow onion": ["vegetable", "bulb"],
            "yellow onions": ["vegetable", "bulb"],
            "white onion": ["vegetable", "bulb"],
            "white onions": ["vegetable", "bulb"],
            "sweet onion": ["vegetable", "bulb"],
            "sweet onions": ["vegetable", "bulb"],
            "pearl onion": ["vegetable", "bulb"],
            "pearl onions": ["vegetable", "bulb"],
            "cipollini onion": ["vegetable", "bulb"],
            "cipollini onions": ["vegetable", "bulb"],
            "leek": ["vegetable", "bulb"],
            "leeks": ["vegetable", "bulb"],
            "scallion": ["vegetable", "bulb"],
            "scallions": ["vegetable", "bulb"],
            "garlic": ["vegetable", "bulb"],
            "celery": ["vegetable", "stem"],
            "cucumber": ["vegetable", "fruit"],
            "cucumbers": ["vegetable", "fruit"],
            "tomato": ["vegetable", "fruit"],
            "tomatoes": ["vegetable", "fruit"],
            "tomato paste": ["vegetable", "fruit"],
            "cherry tomato": ["vegetable", "fruit"],
            "cherry tomatoes": ["vegetable", "fruit"],
            "asparagus": ["vegetable", "stem"],
            "kale": ["vegetable", "leafy"],
            "spinach": ["vegetable", "leafy"],
            "broccoli": ["vegetable", "cruciferous"],
            "broccolini": ["vegetable", "cruciferous"],
            "broccolis": ["vegetable", "cruciferous"],
            "broccolinis": ["vegetable", "cruciferous"],
            "broccoli rabe": ["vegetable", "cruciferous"],
            "broccoli raab": ["vegetable", "cruciferous"],
            "cauliflower": ["vegetable", "cruciferous"],
            "cauliflower rice": ["vegetable", "cruciferous"],
            "brussel sprout": ["vegetable", "cruciferous"],
            "brussel sprouts": ["vegetable", "cruciferous"],
            "zucchini": ["fruit", "squash"],
            "zucchinis": ["fruit", "squash"],
            "lettuce": ["vegetable", "leafy"],
            "romaine lettuce": ["vegetable", "leafy"],
            "iceberg lettuce": ["vegetable", "leafy"],
            "butter lettuce": ["vegetable", "leafy"],
            "boston lettuce": ["vegetable", "leafy"],
            "bibb lettuce": ["vegetable", "leafy"],
            "butter head lettuce": ["vegetable", "leafy"],
            "mixed greens": ["vegetable", "leafy"],
            "arugula": ["vegetable", "leafy"],
            "endive": ["vegetable", "leafy"],
            "endives": ["vegetable", "leafy"],
            "radicchio": ["vegetable", "leafy"],
            "radish": ["vegetable", "root"],
            "radishes": ["vegetable", "root"],
            "turnip": ["vegetable", "root"],
            "turnips": ["vegetable", "root"],
            "artichoke": ["vegetable", "flower"],
            "artichokes": ["vegetable", "flower"],
            "cabbage": ["vegetable", "cruciferous"],
            "bell pepper": ["vegetable", "fruit"],
            "bell peppers": ["vegetable", "fruit"],
            "yellow bell pepper": ["vegetable", "fruit"],
            "yellow bell peppers": ["vegetable", "fruit"],
            "red bell pepper": ["vegetable", "fruit"],
            "red bell peppers": ["vegetable", "fruit"],
            "green bell pepper": ["vegetable", "fruit"],
            "green bell peppers": ["vegetable", "fruit"],
            "jalapeno": ["vegetable", "fruit"],
            "jalapenos": ["vegetable", "fruit"],
            "poblano": ["vegetable", "fruit"],
            "poblanos": ["vegetable", "fruit"],
            "habanero": ["vegetable", "fruit"],
            "habaneros": ["vegetable", "fruit"],
            "serrano": ["vegetable", "fruit"],
            "serranos": ["vegetable", "fruit"],
            "cucumber": ["vegetable", "fruit"],
            "cucumbers": ["vegetable", "fruit"],
            "ghost pepper": ["vegetable", "fruit"],
            "ghost peppers": ["vegetable", "fruit"],
            "carolina reaper": ["vegetable", "fruit"],
            "carolina reapers": ["vegetable", "fruit"],
            "mushroom": ["vegetable", "fungi"],
            "mushrooms": ["vegetable", "fungi"],
            "cremini mushroom": ["vegetable", "fungi"],
            "cremini mushrooms": ["vegetable", "fungi"],
            "portobello mushroom": ["vegetable", "fungi"],
            "portobello mushrooms": ["vegetable", "fungi"],
            "shiitake mushroom": ["vegetable", "fungi"],
            "shiitake mushrooms": ["vegetable", "fungi"],

            # LEGUMES
            "bean": ["legume", "bean"],
            "beans": ["legume", "bean"],
            "black bean": ["legume", "bean"],
            "black beans": ["legume", "bean"],
            "kidney bean": ["legume", "bean"],
            "kidney beans": ["legume", "bean"],
            "pinto bean": ["legume", "bean"],
            "pinto beans": ["legume", "bean"],
            "cannellini bean": ["legume", "bean"],
            "cannellini beans": ["legume", "bean"],
            "refried bean": ["legume", "bean"],
            "refried beans": ["legume", "bean"],
            "white bean": ["legume", "bean"],
            "white beans": ["legume", "bean"],
            "fava bean": ["legume", "bean"],
            "fava beans": ["legume", "bean"],
            "navy bean": ["legume", "bean"],
            "navy beans": ["legume", "bean"],
            "lima bean": ["legume", "bean"],
            "lima beans": ["legume", "bean"],
            "soybean": ["legume", "bean"],
            "soybeans": ["legume", "bean"],
            "edamame": ["legume", "bean"],
            "edamames": ["legume", "bean"],

            "lentil": ["legume", "lentil"],
            "lentils": ["legume", "lentil"],
            "red lentil": ["legume", "lentil"],
            "red lentils": ["legume", "lentil"],
            "green lentil": ["legume", "lentil"],
            "green lentils": ["legume", "lentil"],
            "brown lentil": ["legume", "lentil"],
            "brown lentils": ["legume", "lentil"],
            "yellow lentil": ["legume", "lentil"],
            "yellow lentils": ["legume", "lentil"],
            "black lentil": ["legume", "lentil"],
            "black lentils": ["legume", "lentil"],
            "french lentil": ["legume", "lentil"],
            "french lentils": ["legume", "other"],
            "puy lentil": ["legume", "lentil"],
            "puy lentils": ["legume", "lentil"],
            "canned lentil": ["legume", "lentil"],
            "canned lentils": ["legume", "lentil"],

            "peas": ["legume", "peas"],
            "green pea": ["legume", "pea"],
            "green peas": ["legume", "pea"],
            "split pea": ["legume", "pea"],
            "split peas": ["legume", "pea"],
            "black-eyed pea": ["legume", "pea"],
            "black-eyed peas": ["legume", "pea"],
            "black eyed pea": ["legume", "pea"],
            "black eyed peas": ["legume", "pea"],
            "blackeyed peas": ["legume", "pea"],
            "blackeyed pea": ["legume", "pea"],

            "chickpea": ["legume", "pea"],
            "chickpeas": ["legume", "pea"],
            "garbanzo": ["legume", "bean"],
            "garbanzos": ["legume", "bean"],
            "garbanzo bean": ["legume", "pea"],
            "garbanzo beans": ["legume", "pea"], 
            "can of chickpea": ["legume", "pea"],
            "can of chickpeas": ["legume", "pea"],
            "canned chickpea": ["legume", "pea"],
            "canned chickpeas": ["legume", "pea"],
            "canned garbanzo": ["legume", "pea"],
            "canned garbanzos": ["legume", "pea"],
            "canned garbanzo bean": ["legume", "pea"],
            "canned garbanzo beans": ["legume", "pea"],
            "can of garbanzo": ["legume", "pea"],
            "can of garbanzos": ["legume", "pea"],
            "can of garbanzo bean": ["legume", "pea"],
            "can of garbanzo beans": ["legume", "pea"],
            "canned garbanzo bean": ["legume", "pea"],
            "canned garbanzo beans": ["legume", "pea"],
            "snow pea": ["legume", "pea"],
            "snow peas": ["legume", "pea"],
            "snowpea": ["legume", "pea"],
            "snowpeas": ["legume", "pea"],
            "sugar snap pea": ["legume", "pea"],
            "sugar snap peas": ["legume", "pea"],
            "snap pea": ["legume", "pea"],
            "snap peas": ["legume", "pea"],
            "field pea": ["legume", "pea"],
            "field peas": ["legume", "pea"],
            "cowpea": ["legume", "pea"],
            "cowpeas": ["legume", "pea"],
            "yellow pea": ["legume", "pea"],
            "yellow peas": ["legume", "pea"],
            "garden pea": ["legume", "pea"],
            "garden peas": ["legume", "pea"],
            "pea shoot": ["legume", "pea"],
            "pea shoots": ["legume", "pea"],

            # MEATS
            "egg": ["meat", "egg"],
            "eggs": ["meat", "egg"],
            "egg yolk": ["meat", "egg"],
            "egg yolks": ["meat", "egg"],
            "egg white": ["meat", "egg"],
            "egg whites": ["meat", "egg"],
            "chicken egg": ["meat", "egg"],
            "chicken eggs": ["meat", "egg"],
            "duck egg": ["meat", "egg"],
            "duck eggs": ["meat", "egg"],
            "quail egg": ["meat", "egg"],
            "quail eggs": ["meat", "egg"],

            "chicken": ["meat", "poultry"],
            "chicken breast": ["meat", "poultry"],
            "chicken breasts": ["meat", "poultry"],
            "chicken thigh": ["meat", "poultry"],
            "chicken thighs": ["meat", "poultry"],
            "chicken leg": ["meat", "poultry"],
            "chicken legs": ["meat", "poultry"],
            "chicken wing": ["meat", "poultry"],
            "chicken wings": ["meat", "poultry"],
            "turkey": ["meat", "poultry"],
            "turkey breast": ["meat", "poultry"],
            "turkey breasts": ["meat", "poultry"],
            "turkey thigh": ["meat", "poultry"],
            "turkey thighs": ["meat", "poultry"],
            "turkey leg": ["meat", "poultry"],
            "turkey legs": ["meat", "poultry"],
            "turkey wing": ["meat", "poultry"],
            "turkey wings": ["meat", "poultry"],
            "turkey bacon": ["meat", "poultry"],
            "turkey sausage": ["meat", "poultry"],
            "duck": ["meat", "poultry"],
            "duck breast": ["meat", "poultry"],
            "duck breasts": ["meat", "poultry"],
            "duck thigh": ["meat", "poultry"],
            "duck thighs": ["meat", "poultry"],
            "duck leg": ["meat", "poultry"],
            "duck legs": ["meat", "poultry"],
            "duck wing": ["meat", "poultry"],
            "duck wings": ["meat", "poultry"],
            "duck bacon": ["meat", "poultry"],
            "duck sausage": ["meat", "poultry"],
            "quail": ["meat", "poultry"],
            "quail breast": ["meat", "poultry"],
            "quail breasts": ["meat", "poultry"],
            "quail thigh": ["meat", "poultry"],
            "quail thighs": ["meat", "poultry"],
            "quail leg": ["meat", "poultry"],
            "quail legs": ["meat", "poultry"],
            "quail wing": ["meat", "poultry"],
            "quail wings": ["meat", "poultry"],

            "beef": ["meat", "beef"],
            "grass-fed beef": ["meat", "beef"],
            "grassfed beef": ["meat", "beef"],
            "grass fed beef": ["meat", "beef"],
            "ground beef": ["meat", "beef"],
            "grass-fed ground beef": ["meat", "beef"],
            "grassfed ground beef": ["meat", "beef"],
            "grass fed ground beef": ["meat", "beef"],
            "hamburger": ["meat", "beef"],
            "hamburgers": ["meat", "beef"],
            "hamburger patty": ["meat", "beef"],
            "hamburger patties": ["meat", "beef"],
            "steak": ["meat", "beef"],
            "steaks": ["meat", "beef"],
            "ground beef": ["meat", "beef"],
            "beef chuck": ["meat", "beef"],
            "beef brisket": ["meat", "beef"],
            "beef shank": ["meat", "beef"],
            "beef sirloin": ["meat", "beef"],
            "beef tenderloin": ["meat", "beef"],
            "beef loin": ["meat", "beef"],
            "beef short loin": ["meat", "beef"],
            "beef ribeye": ["meat", "beef"],
            "beef ribeyes": ["meat", "beef"],
            "beef liver": ["meat", "beef"],
            "beef tongue": ["meat", "beef"],
            "beef round": ["meat", "beef"],
            "beef rib": ["meat", "beef"],
            "beef ribs": ["meat", "beef"],
            "beef cheek": ["meat", "beef"],
            "beef cheeks": ["meat", "beef"],
            "t-bone steak": ["meat", "beef"],
            "T-bone steaks": ["meat", "beef"],
            "filet mignon": ["meat", "beef"],
            "filet mignons": ["meat", "beef"],
            "new york strip": ["meat", "beef"],
            "new york strips": ["meat", "beef"],
            "ribeye steak": ["meat", "beef"],
            "ribeye steaks": ["meat", "beef"],
            "sirloin steak": ["meat", "beef"],
            "sirloin steaks": ["meat", "beef"],
            "flank steak": ["meat", "beef"],
            "flank steaks": ["meat", "beef"],
            "skirt steak": ["meat", "beef"],
            "skirt steaks": ["meat", "beef"],
            "hanger steak": ["meat", "beef"],
            "hanger steaks": ["meat", "beef"],
            "porterhouse steak": ["meat", "beef"],
            "porterhouse steaks": ["meat", "beef"],
            "chuck steak": ["meat", "beef"],
            "chuck steaks": ["meat", "beef"],
            "brisket": ["meat", "beef"],

            "bacon": ["meat", "pork"],
            "bacon strips": ["meat", "pork"],
            "bacon slice": ["meat", "pork"],
            "bacon bits": ["meat", "pork"],
            "pork": ["meat", "pork"],
            "pork chop": ["meat", "pork"],
            "pork chops": ["meat", "pork"],
            "pork tenderloin": ["meat", "pork"],
            "pork tenderloins": ["meat", "pork"],
            "pork loin": ["meat", "pork"],
            "pork loins": ["meat", "pork"],
            "pork shoulder": ["meat", "pork"],
            "pork shoulders": ["meat", "pork"],
            "pork belly": ["meat", "pork"],
            "pork bellies": ["meat", "pork"],
            "pork butt": ["meat", "pork"],
            "pork butts": ["meat", "pork"],
            "pork rib": ["meat", "pork"],
            "pork ribs": ["meat", "pork"],
            "pork sausage": ["meat", "pork"],
            "pork sausages": ["meat", "pork"],
            
            "lamb": ["meat", "lamb"],
            "lamb chop": ["meat", "lamb"],
            "lamb chops": ["meat", "lamb"],
            "lamb shank": ["meat", "lamb"],
            "lamb shanks": ["meat", "lamb"],
            "lamb cutlet": ["meat", "lamb"],
            "lamb cutlets": ["meat", "lamb"],
            "lamb leg": ["meat", "lamb"],
            "lamb legs": ["meat", "lamb"],

            "venison": ["meat", "venison"],
            "venison chop": ["meat", "venison"],
            "venison chops": ["meat", "venison"],
            "venison shank": ["meat", "venison"],
            "venison shanks": ["meat", "venison"],
            "venison loin": ["meat", "venison"],
            "venison loins": ["meat", "venison"],
            "venison tenderloin": ["meat", "venison"],
            "venison tenderloins": ["meat", "venison"],
            "venison shoulder": ["meat", "venison"],
            "venison shoulders": ["meat", "venison"],

            "tofu": ["meat", "meat substitute"],
            "tofus": ["meat", "meat substitute"],
            "tofu block": ["meat", "meat substitute"],
            "tofu blocks": ["meat", "meat substitute"],
            "tofu burger": ["meat", "meat substitute"],
            "tofu burgers": ["meat", "meat substitute"],
            "tofu bacon": ["meat", "meat substitute"],
            "tempeh": ["meat", "meat substitute"],
            "seitan": ["meat", "meat substitute"],
            "soy protein": ["meat", "meat substitute"],
            "soy protein powder": ["meat", "meat substitute"],
            "soy protein isolate": ["meat", "meat substitute"],
            "pea protein": ["meat", "meat substitute"],
            "tofurkey": ["meat", "meat substitute"],
            "tofurkey sausage": ["meat", "meat substitute"],
            "tofurkey sausages": ["meat", "meat substitute"],
            "impossible burger": ["meat", "meat substitute"],
            "impossible burgers": ["meat", "meat substitute"],
            "impossible meat": ["meat", "meat substitute"],
            "impossible meats": ["meat", "meat substitute"],
            "impossible sausage": ["meat", "meat substitute"],
            "impossible sausages": ["meat", "meat substitute"],
            "beyond burger": ["meat", "meat substitute"],
            "beyond burgers": ["meat", "meat substitute"],

            # SEAFOOD
            "salmon": ["meat", "fish"],
            "swordfish": ["meat", "fish"],
            "sea bass": ["meat", "fish"],
            "catfish": ["meat", "fish"],
            "halibut": ["meat", "fish"],
            "cod": ["meat", "fish"],
            "tuna": ["meat", "fish"],
            "trout": ["meat", "fish"],
            "snapper": ["meat", "fish"],
            "mahi mahi": ["meat", "fish"],
            "mackerel": ["meat", "fish"],
            "sardine": ["meat", "fish"],
            "sardines": ["meat", "fish"],
            "anchovy": ["meat", "fish"],
            "anchovies": ["meat", "fish"],
            "herring": ["meat", "fish"],
            "carp": ["meat", "fish"],
            "tilapia": ["meat", "fish"],
            "can of tuna": ["meat", "fish"],
            "canned tuna": ["meat", "fish"],
            "can of salmon": ["meat", "fish"],
            "canned salmon": ["meat", "fish"],
            "clam": ["meat", "shellfish"],
            "clams": ["meat", "shellfish"],
            "mussels": ["meat", "shellfish"],
            "shrimp": ["meat", "shellfish"],
            "lobster": ["meat", "shellfish"],
            "lobsters": ["meat", "shellfish"],
            "crab": ["meat", "shellfish"],
            "crabs": ["meat", "shellfish"],
            "imitation crab": ["meat", "shellfish"],
            "oyster": ["meat", "shellfish"],
            "oysters": ["meat", "shellfish"],
            "scallop": ["meat", "shellfish"],
            "scallops": ["meat", "shellfish"],
            
            # DAIRY
            "milk": ["dairy", "milk"],
            "whole milk": ["dairy", "milk"],
            "skim milk": ["dairy", "milk"],
            "nonfat milk": ["dairy", "milk"],
            "butter": ["dairy", "butter"],
            "clarified butter": ["dairy", "butter"],
            "unsalted butter": ["dairy", "butter"],
            "salted butter": ["dairy", "butter"],
            "heavy whipping cream": ["dairy", "cream"],
            "half and half": ["dairy", "cream"],
            "half & half": ["dairy", "cream"],
            "whipped cream": ["dairy", "cream"],
            "light whipped cream": ["dairy", "cream"],
            "lowfat whipped cream": ["dairy", "cream"],
            "margarine": ["dairy", "butter"],
            "cheese": ["dairy", "cheese"],
            "crumbled cheese": ["dairy", "cheese"],
            "shredded cheese": ["dairy", "cheese"],
            "bleu cheese": ["dairy", "cheese"],
            "parmesan cheese": ["dairy", "cheese"],
            "shredded parmesan cheese": ["dairy", "cheese"],
            "cheddar cheese": ["dairy", "cheese"],
            "shredded cheddar cheese": ["dairy", "cheese"],
            "mozzarella cheese": ["dairy", "cheese"],
            "shredded mozzarella cheese": ["dairy", "cheese"],
            "feta cheese": ["dairy", "cheese"],
            "goat cheese": ["dairy", "cheese"],
            "gorgonzola cheese": ["dairy", "cheese"],
            "provolone cheese": ["dairy", "cheese"],
            "swiss cheese": ["dairy", "cheese"],
            "american cheese": ["dairy", "cheese"],
            "pepper jack cheese": ["dairy", "cheese"],
            "monterey jack cheese": ["dairy", "cheese"],
            "colby cheese": ["dairy", "cheese"],
            "muenster cheese": ["dairy", "cheese"],
            "havarti cheese": ["dairy", "cheese"],
            "brie cheese": ["dairy", "cheese"],
            "camembert cheese": ["dairy", "cheese"],
            "cream cheese": ["dairy", "cheese"],
            "light cream cheese": ["dairy", "cheese"],
            "lowfat cream cheese": ["dairy", "cheese"],
            "cottage cheese": ["dairy", "cheese"],
            "lowfat cottage cheese": ["dairy", "cheese"],
            "yogurt": ["dairy", "yogurt"],
            "nonfat yogurt": ["dairy", "yogurt"],
            "lowfat yogurt": ["dairy", "yogurt"],
            "greek yogurt": ["dairy", "yogurt"],
            "nonfat greek yogurt": ["dairy", "yogurt"],
            "lowfat greek yogurt": ["dairy", "yogurt"],
            "sour cream": ["dairy", "other"],
            "light sour cream": ["dairy", "other"],
            "heavy cream": ["dairy", "other"],

            # DAIRY ALTERNATIVES
            "almond milk": ["dairy", "milk substitute"],
            "unsweetened almond milk": ["dairy", "milk substitute"],
            "sweetened almond milk": ["dairy", "milk substitute"],
            "unsweetened vanilla almond milk": ["dairy", "milk substitute"],
            "sweetened vanilla almond milk": ["dairy", "milk substitute"],
            "cashew milk": ["dairy", "milk substitute"],
            "unsweetened cashew milk": ["dairy", "milk substitute"],
            "sweetened cashew milk": ["dairy", "milk substitute"],
            "unsweetened vanilla cashew milk": ["dairy", "milk substitute"],
            "sweetened vanilla cashew milk": ["dairy", "milk substitute"],
            "rice milk": ["dairy", "milk substitute"],
            "soy milk": ["dairy", "milk substitute"],
            "coconut milk": ["dairy", "milk substitute"],
            "almond milk": ["dairy", "milk substitute"],
            "oat milk": ["dairy", "milk substitute"],

            # GRAINS
            "rice": ["grain", "rice"],
            "white rice": ["grain", "rice"],
            "brown rice": ["grain", "rice"],
            "basmati rice": ["grain", "rice"],
            "long grain rice": ["grain", "rice"],
            "short grain rice": ["grain", "rice"],
            "jasmine rice": ["grain", "rice"],
            "wild rice": ["grain", "rice"],
            "wild rice blend": ["grain", "rice"],
            "fried rice": ["grain", "rice"],

            "pasta": ["grain", "pasta"],
            "pastas": ["grain", "pasta"],
            "whole wheat pasta": ["grain", "pasta"],
            "whole wheat pastas": ["grain", "pasta"],
            "whole grain pasta": ["grain", "pasta"],
            "whole grain pastas": ["grain", "pasta"],
            "gluten free pasta": ["grain", "pasta"],
            "gluten free pastas": ["grain", "pasta"],
            "gluten-free pasta": ["grain", "pasta"],
            "angel hair pasta": ["grain", "pasta"],
            "fettuccine pasta": ["grain", "pasta"],
            "penne pasta": ["grain", "pasta"],
            "spaghetti pasta": ["grain", "pasta"],
            "linguine pasta": ["grain", "pasta"],
            "rotini pasta": ["grain", "pasta"],
            "macaroni pasta": ["grain", "pasta"],
            "elbow pasta": ["grain", "pasta"],
            "penne" : ["grain", "pasta"],
            "spaghetti" : ["grain", "pasta"],
            "linguine" : ["grain", "pasta"],
            "rotini" : ["grain", "pasta"],
            "macaroni" : ["grain", "pasta"],
            "elbow" : ["grain", "pasta"],
            "lasagna noodle": ["grain", "pasta"],
            "lasagna noodles": ["grain", "pasta"],
            "lasagna sheet": ["grain", "pasta"],
            "lasagna sheets": ["grain", "pasta"],
            "lasagna": ["grain", "pasta"],
            "bread": ["grain", "bread"],
            "baguette": ["grain", "bread"],
            "french bread": ["grain", "bread"],
            "french baguette": ["grain", "bread"],
            "french roll": ["grain", "bread"],
            "french rolls": ["grain", "bread"],
            "sourdough": ["grain", "bread"],
            "sourdough bread": ["grain", "bread"],
            "whole wheat bread": ["grain", "bread"],
            "white bread": ["grain", "bread"],
            "multigrain bread": ["grain", "bread"],
            "rye bread": ["grain", "bread"],
            "oat bread": ["grain", "bread"],
            "egg bread": ["grain", "bread"],
            "potato bread": ["grain", "bread"],
            "cornbread": ["grain", "bread"],
            "corn bread": ["grain", "bread"],
            "croissant": ["grain", "bread"],
            "croissants": ["grain", "bread"],
            "biscuit": ["grain", "bread"],
            "biscuits": ["grain", "bread"],
            "english muffin": ["grain", "bread"],
            "english muffins": ["grain", "bread"],
            "bagel": ["grain", "bread"],
            "bagels": ["grain", "bread"],
            "tortilla": ["grain", "bread"],
            "tortillas": ["grain", "bread"],
            "corn tortilla": ["grain", "bread"],
            "corn tortillas": ["grain", "bread"],
            "flour tortilla": ["grain", "bread"],
            "flour tortillas": ["grain", "bread"],
            "flatbread": ["grain", "bread"],
            "flatbreads": ["grain", "bread"],
            "pita": ["grain", "bread"],
            "pitas": ["grain", "bread"],
            "naan": ["grain", "bread"],
            "naans": ["grain", "bread"],
            "whole wheat naan": ["grain", "bread"],
            "hamburger bun": ["grain", "bread"],
            "hamburger buns": ["grain", "bread"],
            "hot dog bun": ["grain", "bread"],
            "hot dog buns": ["grain", "bread"],
            "hawaiian roll": ["grain", "bread"],
            "hawaiian rolls": ["grain", "bread"],
            "english roll": ["grain", "bread"],
            "english rolls": ["grain", "bread"],
            "foccacia": ["grain", "bread"],
            "foccacia bread": ["grain", "bread"],
            "foccacia roll": ["grain", "bread"],
            "foccacia rolls": ["grain", "bread"],

            "egg noodle": ["grain", "pasta"],
            "egg noodles": ["grain", "pasta"],
            "glass noodle": ["grain", "pasta"],
            "glass noodles": ["grain", "pasta"],
            "ramen noodle": ["grain", "pasta"],
            "ramen noodles": ["grain", "pasta"],
            "rice noodle": ["grain", "pasta"],
            "rice noodles": ["grain", "pasta"],
            "soba noodle": ["grain", "pasta"],
            "soba noodles": ["grain", "pasta"],
            "udon noodle": ["grain", "pasta"],
            "udon noodles": ["grain", "pasta"],
            "oatmeal": ["grain", "oat"],
            "rolled oats": ["grain", "oat"],
            "steel cut oats": ["grain", "oat"],
            "rolled oatmeal": ["grain", "oat"],
            "steel cut oatmeal": ["grain", "oat"],
            "corn": ["grain", "corn"],
            "quinoa": ["grain", "other"],
            "barley": ["grain", "other"],
            "rye": ["grain", "other"],
            "couscous": ["grain", "other"],
            "popcorn": ["grain", "other"],
            "millet": ["grain", "other"],
            "flour": ["grain", "flour"],
            "all-purpose flour": ["grain", "flour"],
            "whole wheat flour": ["grain", "flour"],
            "whole grain flour": ["grain", "flour"],
            "bread flour": ["grain", "flour"],
            "semolina flour": ["grain", "flour"],
            "semolina": ["grain", "flour"],
            "cake flour": ["grain", "flour"],
            "self-rising flour": ["grain", "flour"],
            "cornstarch": ["grain", "flour"],
            "corn starch": ["grain", "flour"],
            "cornmeal": ["grain", "flour"],
            "corn meal": ["grain", "flour"],

            # NUTS
            "almond": ["nut", "other"],
            "almonds": ["nut", "other"],
            "roasted almond": ["nut", "other"],
            "roasted almonds": ["nut", "other"],
            "peanut": ["nut", "other"],
            "peanuts": ["nut", "other"],
            "roasted peanut": ["nut", "other"],
            "roasted peanuts": ["nut", "other"],
            "unsalted peanut": ["nut", "other"],
            "unsalted peanuts": ["nut", "other"],
            "salted peanut": ["nut", "other"],
            "salted peanuts": ["nut", "other"],
            "cashew": ["nut", "other"],
            "cashews": ["nut", "other"],
            "pisatchio": ["nut", "other"],
            "pistachios": ["nut", "other"],
            "macadamia": ["nut", "other"],
            "macadamia nut": ["nut", "other"],
            "macadamia nuts": ["nut", "other"],
            "hazelnut": ["nut", "other"],
            "hazelnuts": ["nut", "other"],
            "chestnut": ["nut", "other"],
            "chestnuts": ["nut", "other"],
            "pine nut": ["nut", "other"],
            "pine nuts": ["nut", "other"],
            "brazil nut": ["nut", "other"],
            "brazil nuts": ["nut", "other"],
            "walnut": ["nut", "other"],
            "walnuts": ["nut", "other"],
            "pecan": ["nut", "other"],
            "pecans": ["nut", "other"],
            "peanut butter": ["nut", "nut butter"],
            "almond butter": ["nut", "nut butter"],
            "cashew butter": ["nut", "nut butter"],
            "pumpkin seed": ["nut", "seed"],
            "pumpkin seeds": ["nut", "seed"],
            "sunflower seed": ["nut", "seed"],
            "sunflower seeds": ["nut", "seed"],
            "sesame seed": ["nut", "seed"],
            "sesame seeds": ["nut", "seed"],
            "almond flour": ["nut", "flour"],

            # OILS
            "vegetable oil": ["oil", "vegetable-based"],
            "sesame oil": ["oil", "seed-based"],
            "sunflower oil": ["oil", "seed-based"],
            "canola oil": ["oil", "seed-based"],
            "olive oil": ["oil", "vegetable-based"],
            "coconut oil": ["oil", "vegetable-based"],
            "avocado oil": ["oil", "vegetable-based"],
            "extra virgin olive oil": ["oil", "vegetable-based"],
            "peanut oil": ["oil", "seed-based"],
            "truffle oil": ["oil", "vegetable-based"],
            "chili oil": ["oil", "vegetable-based"],
            "salmon oil": ["oil", "animal-based"],
            "wild alaskan salmon oil": ["oil", "animal-based"],
            "cod liver oil": ["oil", "animal-based"],
            "omega-3 oil": ["oil", "animal-based"],
            "fish oil": ["oil", "animal-based"],
            "lard": ["oil", "animal-based"],
            "duck fat": ["oil", "animal-based"],
            "goose fat": ["oil", "animal-based"],
            "tallow": ["oil", "animal-based"],
            "beef tallow": ["oil", "animal-based"],
            "chicken fat": ["oil", "animal-based"],
            "ghee": ["oil", "animal-based"],
            "suet": ["oil", "animal-based"],
            "grass-fed ghee": ["oil", "animal-based"],
            "grassfed ghee": ["oil", "animal-based"],
            "grass fed ghee": ["oil", "animal-based"],

            # SPICES
            "salt": ["spice", "salt"],
            "Kosher salt": ["spice", "salt"],
            "kosher salt": ["spice", "salt"],
            "table salt": ["spice", "salt"],
            "sea salt": ["spice", "salt"],
            "iodized salt": ["spice", "salt"],
            "black salt": ["spice", "salt"],
            "himilayan salt": ["spice", "salt"],
            "pink salt": ["spice", "salt"],
            "garlic salt": ["spice", "salt"],
            "onion salt": ["spice", "salt"],
            "cinnamon": ["spice", "bark"],
            "cumin": ["spice", "other"],
            "coriander": ["spice", "other"],
            "paprika": ["spice", "other"],
            "cayenne": ["spice", "other"],
            "chili powder": ["spice", "other"],
            "curry powder": ["spice", "other"],
            "turmeric": ["spice", "other"],
            "ginger": ["spice", "root"],
            "nutmeg": ["spice", "other"],
            "cloves": ["spice", "other"],
            "allspice": ["spice", "other"],
            "cardamom": ["spice", "other"],
            "oregano": ["spice", "herb"],
            "thyme": ["spice", "herb"],
            "rosemary": ["spice", "herb"],
            "sage": ["spice", "herb"],
            "basil": ["spice", "herb"],
            "mint": ["spice", "herb"],
            "parsley": ["spice", "herb"],
            "cilantro": ["spice", "herb"],
            "dill": ["spice", "herb"],
            "tarragon": ["spice", "herb"],
            "garlic powder": ["spice", "other"],
            "onion powder": ["spice", "other"],
            "cayenne pepper": ["spice", "pepper"],
            "lemon pepper": ["spice", "pepper"],
            "fresh tarragon": ["spice", "herb"],
            "pepper": ["spice", "pepper"],
            "ground pepper": ["spice", "pepper"],
            "black pepper": ["spice", "pepper"],
            "ground black pepper": ["spice", "pepper"],
            "peppercorns": ["spice", "seed"],

            # FRUITS
            "grapefruit": ["fruit", "citrus"],
            "grapefruits": ["fruit", "citrus"],
            "lime": ["fruit", "citrus"],
            "limes": ["fruit", "citrus"],
            "lemon": ["fruit", "citrus"],
            "lemons": ["fruit", "citrus"],
            "strawberry": ["fruit", "berry"],
            "strawberries": ["fruit", "berry"],
            "blueberry": ["fruit", "berry"],
            "blueberries": ["fruit", "berry"],
            "blackberry": ["fruit", "berry"],
            "blackberries": ["fruit", "berry"],
            "raspberry": ["fruit", "berry"],
            "raspberries": ["fruit", "berry"],
            "banana": ["fruit", "tropical"],
            "bananas": ["fruit", "tropical"],
            "apple": ["fruit", "pome"],
            "apples": ["fruit", "pome"],
            "granny smith apple": ["fruit", "pome"],
            "granny smith apples": ["fruit", "pome"],
            "fuji apple": ["fruit", "pome"],
            "fuji apples": ["fruit", "pome"],
            "red delicious apple": ["fruit", "pome"],
            "red delicious apples": ["fruit", "pome"],
            "golden delicious apple": ["fruit", "pome"],
            "golden delicious apples": ["fruit", "pome"],
            "honeycrisp apple": ["fruit", "pome"],
            "honeycrisp apples": ["fruit", "pome"],
            "macintosh apple": ["fruit", "pome"],
            "macintosh apples": ["fruit", "pome"],
            "orange": ["fruit", "citrus"],
            "oranges": ["fruit", "citrus"],
            "pear": ["fruit", "pome"],
            "pears": ["fruit", "pome"],
            "grape": ["fruit", "berry"],
            "grapes": ["fruit", "berry"],
            "watermelon": ["fruit", "melon"],
            "watermelons": ["fruit", "melon"],
            "cantaloupe": ["fruit", "melon"],
            "cantaloupes": ["fruit", "melon"],
            "honeydew": ["fruit", "melon"],
            "honeydews": ["fruit", "melon"],
            "kiwi": ["fruit", "tropical"],
            "kiwis": ["fruit", "tropical"],
            "mango": ["fruit", "tropical"],
            "mangos": ["fruit", "tropical"],
            "pineapple": ["fruit", "tropical"],
            "pineapples": ["fruit", "tropical"],
            "peach": ["fruit", "stone"],
            "peaches": ["fruit", "stone"],
            "plum": ["fruit", "stone"],
            "plums": ["fruit", "stone"],
            "apricot": ["fruit", "stone"],
            "apricots": ["fruit", "stone"],
            "cherry": ["fruit", "stone"],
            "cherries": ["fruit", "stone"],
            "fig": ["fruit", "other"],
            "figs": ["fruit", "other"],
            "date": ["fruit", "other"],
            "dates": ["fruit", "other"],
            "pomegranate": ["fruit", "other"],
            "pomegranates": ["fruit", "other"],
            "coconut": ["fruit", "other"],
            "coconuts": ["fruit", "other"],
            "passion fruit": ["fruit", "other"],
            "passion fruits": ["fruit", "other"],
            "dragon fruit": ["fruit", "other"],
            "dragon fruits": ["fruit", "other"],
            "guava": ["fruit", "other"],
            "guavas": ["fruit", "other"],
            "star fruit": ["fruit", "other"],
            "star fruits": ["fruit", "other"],
            "lychee": ["fruit", "other"],
            "lychees": ["fruit", "other"],
            "persimmon": ["fruit", "other"],
            "persimmons": ["fruit", "other"],
            "papaya": ["fruit", "tropical"],
            "papayas": ["fruit", "tropical"],
            "cranberry": ["fruit", "berry"],
            "cranberries": ["fruit", "berry"],
            "raisin": ["fruit", "other"],
            "raisins": ["fruit", "other"],
            "prune": ["fruit", "other"],
            "prunes": ["fruit", "other"],
            "currant": ["fruit", "berry"],
            "currants": ["fruit", "berry"],
            "elderberry": ["fruit", "berry"],
            "elderberries": ["fruit", "berry"],
            "goji berry": ["fruit", "berry"],
            "goji berries": ["fruit", "berry"],
            "acai": ["fruit", "berry"],
            "acai berry": ["fruit", "berry"],
            "acai berries": ["fruit", "berry"],
            "boysenberry": ["fruit", "berry"],
            "boysenberries": ["fruit", "berry"],

            # BEVERAGES
            "water": ["beverage", "water"],
            "coffee": ["beverage", "coffee"],
            "decaf coffee": ["beverage", "coffee"],
            "espresso": ["beverage", "coffee"],
            "tea": ["beverage", "tea"],
            "soda": ["beverage", "soda"],
            "orange juice": ["beverage", "juice"],
            "apple juice": ["beverage", "juice"],
            "grape juice": ["beverage", "juice"],
            "mango juice": ["beverage", "juice"],
            "pineapple juice": ["beverage", "juice"],
            "lime juice": ["beverage", "juice"],
            "lemon juice": ["beverage", "juice"],
            "lemonade": ["beverage", "juice"],
            "limeade": ["beverage", "juice"],
            "chicken broth": ["beverage", "soup"],
            "beef broth": ["beverage", "soup"],
            "vegetable broth": ["beverage", "soup"],
            "broth": ["beverage", "soup"],
            "stock": ["beverage", "soup"],
            "beer": ["beverage", "beer"],
            "ale": ["beverage", "beer"],
            "lager": ["beverage", "beer"],
            "stout": ["beverage", "beer"],
            "pilsner": ["beverage", "beer"],
            "porter": ["beverage", "beer"],
            "IPA": ["beverage", "beer"],
            "india pale ale": ["beverage", "beer"],
            "ipa": ["beverage", "beer"],
            "wine": ["beverage", "wine"],
            "white wine": ["beverage", "wine"],
            "red wine": ["beverage", "wine"],
            "pinot noir": ["beverage", "wine"],
            "chardonnay": ["beverage", "wine"],
            "sauvignon blanc": ["beverage", "wine"],
            "merlot": ["beverage", "wine"],
            "cabernet sauvignon": ["beverage", "wine"],
            "rosé": ["beverage", "wine"],
            "rose": ["beverage", "wine"],
            "rose wine" : ["beverage", "wine"],
            "champagne": ["beverage", "wine"],
            "sparkling wine": ["beverage", "wine"],
            "dessert wine": ["beverage", "wine"],
            "cooking wine": ["beverage", "wine"],

            # CONDIMENTS/SAUCES
            "vinegar": ["condiment/sauce", "vinegar"],
            "white wine vinegar": ["condiment/sauce", "vinegar"],
            "balsamic vinegar": ["condiment/sauce", "vinegar"],
            "red wine vinegar": ["condiment/sauce", "vinegar"],
            "apple cider vinegar": ["condiment/sauce", "vinegar"],
            "distilled vinegar": ["condiment/sauce", "vinegar"],
            "rice vinegar": ["condiment/sauce", "vinegar"],
            "white vinegar": ["condiment/sauce", "vinegar"],
            "fish sauce": ["condiment/sauce", "other"],
            "ketchup": ["condiment/sauce", "other"],
            "reduced-sugar ketchup": ["condiment/sauce", "other"],
            "reduced sugar ketchup": ["condiment/sauce", "other"],
            "low-sugar ketchup": ["condiment/sauce", "other"],
            "low sugar ketchup": ["condiment/sauce", "other"],
            "sugar-free ketchup": ["condiment/sauce", "other"],
            "sugar free ketchup": ["condiment/sauce", "other"],
            "low-sodium ketchup": ["condiment/sauce", "other"],
            "low sodium ketchup": ["condiment/sauce", "other"],
            "sodium-free ketchup": ["condiment/sauce", "other"],
            "sodium free ketchup": ["condiment/sauce", "other"],
            "relish": ["condiment/sauce", "other"],
            "mustard": ["condiment/sauce", "other"],
            "dijon mustard": ["condiment/sauce", "other"],
            "yellow mustard": ["condiment/sauce", "other"],
            "honey mustard": ["condiment/sauce", "other"],
            "mayonnaise": ["condiment/sauce", "other"],
            "light mayonnaise": ["condiment/sauce", "other"],
            "lowfat mayonnaise": ["condiment/sauce", "other"],
            "low-fat mayonnaise": ["condiment/sauce", "other"],
            "low fat mayonnaise": ["condiment/sauce", "other"],
            "fat-free mayonnaise": ["condiment/sauce", "other"],
            "fat free mayonnaise": ["condiment/sauce", "other"],
            "mayo": ["condiment/sauce", "other"],
            "light mayo": ["condiment/sauce", "other"],
            "lowfat mayo": ["condiment/sauce", "other"],
            "low-fat mayo": ["condiment/sauce", "other"],
            "low fat mayo": ["condiment/sauce", "other"],
            "fat-free mayo": ["condiment/sauce", "other"],
            "fat free mayo": ["condiment/sauce", "other"],
            "miracle whip": ["condiment/sauce", "other"],
            "miracle whip light": ["condiment/sauce", "other"],
            "miracle whip fat-free": ["condiment/sauce", "other"],
            "miracle whip lowfat": ["condiment/sauce", "other"],
            
            "ranch": ["condiment/sauce", "other"],
            "ranch dressing": ["condiment/sauce", "salad dressing"],
            "caesar dressing": ["condiment/sauce", "salad dressing"],
            "thousand island dressing": ["condiment/sauce", "salad dressing"],
            "blue cheese dressing": ["condiment/sauce", "salad dressing"],
            "italian dressing": ["condiment/sauce", "salad dressing"],
            "vinaigrette": ["condiment/sauce", "salad dressing"],
            "vinaigrette dressing": ["condiment/sauce", "salad dressing"],
            "sesame dressing": ["condiment/sauce", "salad dressing"],
            "honey mustard dressing": ["condiment/sauce", "salad dressing"],
            "balsamic dressing": ["condiment/sauce", "salad dressing"],
            "balsamic vinaigrette": ["condiment/sauce", "salad dressing"],
            "soy sauce": ["condiment/sauce", "other"],
            "BBQ sauce": ["condiment/sauce", "other"],
            "bbq sauce": ["condiment/sauce", "other"],
            "barbecue sauce": ["condiment/sauce", "other"],
            "hot sauce": ["condiment/sauce", "other"],
            "sriracha": ["condiment/sauce", "other"],
            "salsa": ["condiment/sauce", "other"],

            # SWEETENERS
            "sugar": ["sweetener", "sugar"],
            "brown sugar": ["sweetener", "sugar"],
            "powdered sugar": ["sweetener", "sugar"],
            "cane sugar": ["sweetener", "sugar"],
            "granulated sugar": ["sweetener", "sugar"],
            "coconut sugar": ["sweetener", "sugar"],
            "confectioners' sugar": ["sweetener", "sugar"],
            "confectioners sugar": ["sweetener", "sugar"],
            "confectioner's sugar": ["sweetener", "sugar"],
            "coconut palm sugar": ["sweetener", "sugar"],
            "coconut sugar": ["sweetener", "sugar"],
            "date sugar": ["sweetener", "sugar"],
            "corn syrup": ["sweetener", "syrup"],
            "high fructose corn syrup": ["sweetener", "syrup"],
            "honey": ["sweetener", "honey"],
            "organic honey": ["sweetener", "honey"],
            "maple syrup": ["sweetener", "syrup"],
            "maple sugar": ["sweetener", "sugar"],
            "agave": ["sweetener", "nectar"],
            "agave nectar": ["sweetener", "nectar"],
            "stevia": ["sweetener", "sugar substitute"],
            "Sweet'n Low": ["sweetener", "sugar substitute"],
            "sweet'n low": ["sweetener", "sugar substitute"],
            "splenda": ["sweetener", "sugar substitute"],
            "Splenda": ["sweetener", "sugar substitute"],
            "truvia": ["sweetener", "sugar substitute"],
            "Xylitol": ["sweetener", "sugar alcohol"],
            "Erythritol": ["sweetener", "sugar alcohol"],
            "Sorbitol": ["sweetener", "sugar alcohol"],
            "Maltitol": ["sweetener", "sugar alcohol"],
            "xylitol": ["sweetener", "sugar alcohol"],
            "erythritol": ["sweetener", "sugar alcohol"],
            "sorbitol": ["sweetener", "sugar alcohol"],
            "maltitol": ["sweetener", "sugar alcohol"],
            "chocolate chips": ["sweetener", "other"],

            # OTHER
            "pizza": ["other", "other"],
            "chocolate": ["other", "other"],
            "ice cream": ["other", "other"],
            "cake": ["other", "other"],
            "cooking spray": ["other", "other"],
            "baking sheets": ["other", "baking"],
            "baking powder": ["other", "baking"],
            "baking soda": ["other", "baking"],
            "yeast": ["other", "baking"],
            "baking yeast": ["other", "baking"],
            "active dry yeast": ["other", "baking"],
            "instant yeast": ["other", "baking"],
            "baking chocolate": ["other", "baking"]
            }
        
        self.categories = {}

        for key in self.food_catalog:

            major_category = self.food_catalog[key][0]
            minor_category = self.food_catalog[key][1]

            # get the current list of values for the primary category 
            current_set = self.categories.get(major_category, set())

            # Append "brown rice" to the list
            current_set.add(minor_category)

            # Update the major category key with the new updated set of minory categories
            self.categories[major_category] = current_set

        # Convert each set to a list
        for key in self.categories:
            # If "other" is a category, remove "other" from the list and add it to the end (This is for the benefit of NLP model)
            if "other" not in self.categories[key]:
                self.categories[key] = list(self.categories[key])
            else:
                self.categories[key].remove("other")
                self.categories[key] = list(self.categories[key])
                self.categories[key].append("other")